lib/workers/testbot.ts, package-lock.json, package.json
This is a CDS device, similar to the RT RPI 300
that has been recently added in the previous merged
commit.
Signed-off-by: Alexandru Costache <alexandru@balena.io>
Added as requested in internal thread https://www.flowdock.com/app/rulemotion/r-resinos/threads/_kUatH1oNk-uYMhQSwmzHphpnKq
=> lib: Add RPI3 Neuron CDS to leviathan supported devices

Dockerfile.template, docker-compose.qemu.yml, docker-compose.yml, entry.sh, lib/workers/qemu.ts
Reverts balena-os/leviathan-worker#21
The original PR is not compatible with existing balenaOS releases and is blocking testing. This feature should be re-implemented with a toggle that is disabled by default.
=> Revert software raid support

.github/workflows/flowzone.yml
This can be useful to visualize in the logs what env vars were set, what worker image was pulled, etc.
Signed-off-by: Kyle Harding <kyle@balena.io>
=> Add make config to e2e suite to dump merged compose files

lib/workers/qemu.ts
Allow for booting works from external storage, with blank internal storage available for flashing. This will enable flasher images to be tested without unwrapping.
Signed-off-by: Joseph Kogut <joseph@balena.io>
=> qemu: add internal/external storage

.github/workflows/flowzone.yml
Use regex to set the worker release commit in the compose file before running e2e tests.
This allows us to deprecate the WORKER_RELEASE env var.
Signed-off-by: Kyle Harding <kyle@balena.io>
=> e2e: substitute the worker release in the compose file

config/default.js, lib/workers/qemu.ts, typings/worker.d.ts
This adds onto the previous `qemu-flasher` PR (now merged), which allowed for testing flasher images without unwrapping them.
This PR adds on support for testing secure boot enabled flasher images.
=> Qemu flasher secureboot

Dockerfile.template, bin/index.ts, lib/helpers/graphics.ts, lib/helpers/index.ts, lib/index.ts, lib/workers/qemu.ts, package-lock.json, package.json, typings/worker.d.ts
The PR breaks the worker server when running on autokit. Improvements need to be made to make it more stable, then only the dependencies can be updated. Reverting this update till then. 
Reverts balena-os/leviathan-worker#50
=> Revert "Upgrade dependencies to node v18"

lib/workers/qemu.ts
QEMU defaults to a static MAC address of 52:52:00:12:34:56. This can cause conflicts when multiple workers are running on the same machine.
Randomize the MAC to prevent networking conflicts.
=> qemu: randomize mac addr

lib/workers/qemu.ts
quick fix to stop the qemu working crashing when accidently giving networkWireless: true - this attribute isn't used anyway for this worker, and it simplifies the test suit to just ignore it
=> stop crash when using networkWireless: true

Dockerfile.template, lib/workers/qemu.ts
After upgrading the alpine base image, the AAVMF vars file is no longer installed by the qemu-system-aarch64 package, but rather qemu-system-arm.
=> Dockerfile: install qemu-system-arm

lib/workers/qemu.ts
Guests may write persistent variables to firmware in cases such as changing the boot order or configuring secure boot keys. These variables are backed by a file configured as part of pflash, typically shipped with edk2.
When reflashing, variables may need to be reset, or previous configuration may stop the flashing process, such as secure boot rejecting the signature of the flasher's bootloader.
Copy the edk2 vars file from the usr directory to a runtime location, allowing the flash method to reset this backing file.
=> qemu: erase firmware vars on flash

lib/workers/qemu.ts
This property appears to alter the behavior of the automatic boot device selection of OVMF in such a way that the internal disk is no longer booted as expected automatically after flashing with the external disk still attached. Remove it.
=> qemu: remove bootindex from external disk

lib/config.ts, lib/index.ts, lib/workers/qemu.ts, package-lock.json, package.json, typings/worker.d.ts
PR to enable `executeCommandInHostOs()` in tests to use serial terminal as an option, instead of ssh
The main use cases were:
- in cases where we have a connectivity issue, we have no way into the DUT, this would allow for that. Currently we jsut get "could not reoslve xyz.local" and we can't determine if the DUT didn't boot or there was a connection issue
- we will actually be able to do the dev/prod serial tests (we're not at the moment)
- will allow us to do tests where we disrupt the network connectivity - e.g to test the NM recovery mechanism alex and zahari were discussing
Notes on implementation:
- the "execute this command on serial terminal at device `/dev/*` and collect the exit code and response" is implemented here: https://www.npmjs.com/package/@balena/node-serial-terminal/v/0 …
=> enable serial terminal interaction

lib/workers/autokit.ts
avoid container crashlooping when no secondary, boot switch relay connected, which is most cases
=> change defaults for autokit worker

lib/index.ts
replace the hard coded balena api url with the device env variable instead. Needed to enable using workers on different environments (staging/balena machine)
=> use balena api env var instead of hard-coding

lib/workers/qemu.ts
Remove default interfaces like CDROMs, floppy disk and other to avoid boot order problems and guarantee the system boots with only one block disk so the migration is always performed.
Fixes balena-os/balena-generic/#265
=> workers/qemu: start qemu without default interfaces

.github/workflows/balenamachine-push.yml
Due to how deploy-to-balena operates using a finalize action only lets you finalize releases not push new ones AFAIK. 
So creating a new action to push only when PRs are closed. 
=> patch: Create new action for balenamachine push

Dockerfile.template, docker-compose.yml, entry.sh, package-lock.json, package.json
This required:
- adding docker in docker to the worker container - this is because jetson-flash uses a container
- adding the jetson-flash device type flashing logic to the autokit sdk - code here builds and starts the jetson flash container
- docker in docker is not started with the qemu worker - as it is not needed.
=> enable jetson-flash device types

Dockerfile.template, package-lock.json, package.json
Removed all git clones from the dockerfile, instead installing relevant tooling in the autokit initialisation, for several reasons:
- the git clones were often resulting in errors during the container build on balena cloud builders
- these tools are dependent on the specific hardware connected to the autokit - in most cases they won't be needed - it makes no sense to have them in this dockerfile
=> remove all git clones from dockerfile

Dockerfile.template
Fixes bug in Alpine's OVMF binaries that causes firmware to not measure data during boot into TPM PCRs.
=> Install OVMF from debian

.github/workflows/flowzone.yml
- remove personal fleet as it was unused and just another place for the balena push CI action to fail
- add partners rig for external autokit users
=> Add testbot-rig-partners for Leviathan-worker deploy

package-lock.json, package.json
includes fixes for selecting wifi AP channel, updates for the iot-gate-imx8 flashing tools and new linux gmbh revision
=> update autokit to 1.0.37

.github/renovate.json
The config shared by balena-os is tuned for yocto-device-type repositories and not appropriate for generic and nodeJS repos.
=> Extend renovate config from balena-io

Dockerfile.template
balenaOS 6 and later enables module zstd module compression by default
See: https://balena.zulipchat.com/#narrow/stream/403752-channel.2Fsupport-help/topic/Supervisor.20ipv4.2Bipv6.20state/near/469348228
See: https://balena.fibery.io/Work/Project/Kernel-module-compression-452
=> Install kmod from alpine repositories with zstd module support

.github/workflows/flowzone.yml
Superseding #131
- Alters workflow triggers: Removes PRT 
- Uses GitHub environments, and relevant vars and secrets set by the environment
- Remove environment switcher
- Eliminates a need to override secrets
- Alters security preference for persisting creds in the checkout action
=> patch: Change workflow triggers & use env secrets

package-lock.json, package.json
This is to fix builds with node 18.20.5 + python > 3.11
Depends-on: https://github.com/balena-io-hardware/autokit-interface-sw/pull/97
=> Update autokit to 1.1.2 

Dockerfile.template
=> Dockerfile: update OVMF base image to debian:bookworm-20241223

package-lock.json, package.json
to include the new Jetson Nano based device-types.
=> leviathan-worker: Bump autokit to v1.2.3
