lib/index.ts

This fixes the problem, however it increases the flashing time. Short term fix as moving the core back on to the testbot would probably also solve this problem
Signed-off-by: Ryan Cooke <ryan@balena.io>
Resolves: https://github.com/balena-os/leviathan-worker/issues/4

send image before flashing

---

lib/workers/qemu.ts

https://wiki.qemu.org/Documentation/Platforms/ARM
Signed-off-by: Kyle Harding <kyle@balena.io>
Resolves: https://github.com/balena-os/meta-balena/issues/2714

patch: Add display device for aarch64

---

lib/workers/testbot.ts
package-lock.json
package.json

Signed-off-by: Alexandru Costache <alexandru@balena.io>
Connects to:
- https://github.com/balena-io-hardware/testbotsdk/pull/45
- https://github.com/balena-os/balena-jetson/issues/332

package: Update testbotsdk to include TX2 support

---

lib/workers/testbot.ts
package-lock.json
package.json

Signed-off-by: Florin Sarbu <florin@balena.io>

package: Update testbotsdk to include Unipi Neuron RPi4 support

---

package-lock.json
package.json

Signed-off-by: Alexandru Costache <alexandru@balena.io>

package-lock: Update testbotsdk for NRT flashing

---

lib/workers/testbot.ts
package-lock.json
package.json

Signed-off-by: Alexandru Costache <alexandru@balena.io>
Connects-to and requires: https://github.com/balena-io/contracts/pull/327

lib: Add RockPro64 to the leviathan

---

.github/workflows/flowzone.yml

Signed-off-by: Kyle Harding <kyle@balena.io>

Prevent e2e tests on closed events

---

Dockerfile.template
config/default.js
docker-compose.yml
entry.sh
lib/index.ts
lib/workers/autokit.ts
lib/workers/qemu.ts
lib/workers/testbot.ts
package-lock.json
package.json
typings/worker.d.ts

Change-type: minor
Signed-off-by: Ryan Cooke <ryan@balena.io>

add autokit worker

---

lib/workers/qemu.ts

Instead of expecting a raw image to be written to disk, detect and run the flasher image in QEMU.
Signed-off-by: Joseph Kogut <joseph@balena.io>

qemu: run flasher image in flash()

---

package-lock.json
package.json

Signed-off-by: Ryan Cooke <ryan@balena.io>

bump autokit to 1.0.6

---

Dockerfile.template
bin/index.ts
lib/helpers/graphics.ts
lib/helpers/index.ts
lib/index.ts
lib/workers/qemu.ts
package-lock.json
package.json
typings/worker.d.ts

- Add non-null assertion operation for possibly undefined
- minor: Update dependencies & node version v18
- Update Dockerfile to node v18

Upgrade dependencies to node v18

---

Dockerfile.template
package-lock.json
package.json

Update node and deps to v16

---

lib/index.ts

set default if no API URL provided

---

package-lock.json
package.json

bump testbot-sdk for jetson fix

---

lib/workers/qemu.ts

https://github.com/balena-os/leviathan-worker/pull/63 introduced a regression that would cause the secureboot test to fail. The cause was that this test assumed that the DUT serial output was still being written to a file https://github.com/balena-os/meta-balena/blob/master/tests/suites/os/tests/secureboot/index.js#L39 , when it in fact was no longer.
This PR now writes the serial output to a file, as well as connects it to a terminal interface to allow for serial commands to be sent to the DUT. This is done by creating a pty chardev - with a logfile, and then outputting the serial to that cahrdev. This way we still have a terminal to connect to and have a file with all output, achieving both the old and new behaviour.
Additionally, the QEMU_DEBUG option was causing a problem after …

qemu: write serial TX to file again

---

.github/actions/finalize/action.yml

Composite actions need a shell property 

patch: Add shell to finalize action

---

.github/actions/finalize/action.yml
.github/workflows/flowzone.yml

Adding a delay to give time for finalization steps to run, release to be finalized and then push to BM

patch: Delay balenaMachine push to finalize releases

---

.github/actions/finalize/action.yml

patch: Add debug to balenaMachine balena push

---

package-lock.json
package.json

Mainly to enable alternative SD mux

bump autokit sdk to 1.0.10

---

Dockerfile.template
package-lock.json
package.json

add crelay support

---

Dockerfile.template
lib/workers/autokit.ts
package-lock.json
package.json

add iot-gate devices

---

package-lock.json
package.json

update autokit to 1.0.19

---

.github/workflows/flowzone.yml

add deploy to bm x86 rig

---

.github/workflows/flowzone.yml

Created a matrix to push worker app to multiple fleets in Balena Machine, soft reverting #103 

patch: Deduplicate GitHub Action steps with matrix

---

lib/index.ts
lib/workers/autokit.ts
lib/workers/qemu.ts
lib/workers/testbot.ts
package-lock.json
package.json
typings/worker.d.ts

- adds keyboard emulation needed for up board device type
- adds video livestream endpoint for help debugging - live stream viewable by public url `/livestream`
- adds fix to ensure port forwarding is enabled during network setup

add keyboard and video stream endpoints and enable up-board

---

package-lock.json
package.json

contains patch for sdwire mux board setup

bump autokit to 1.0.24

---

.github/workflows/flowzone.yml

Add x86 partner fleet to balena push fleet list

---

package-lock.json
package.json

bump autokit to 1.0.29

---

package-lock.json
package.json

To include support for Seeed J3010 flashing

package: Bump autokit to v1.0.30

---

package-lock.json
package.json

bump autokit to 1.0.34

---

renovate.json

A new one was added in the .github directory via https://github.com/balena-os/leviathan-worker/pull/122

Delete old renovate.json

---

lib/workers/qemu.ts

workers: qemu: listen for qmp connections in /run

---

package-lock.json
package.json

package-lock: Bump autokit-interface-sw to 1.1.4

---

package-lock.json
package.json

This is to add support for a new device type

Change autokit to 1.2.1

---

.github/workflows/flowzone.yml

workflows: Add deploys to aarch64 testbot fleets
